version: '3.1'
services:
  postgres-server:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  validation-service-native:
    build:
      context: ./validation-service
      dockerfile: docker/native/Dockerfile
    ports:
      - "8082:8082"
  customer-service-native:
    build:
      context: ./customer-service
      dockerfile: docker/native/Dockerfile
    depends_on:
      - postgres-server
      - validation-service-native
    ports:
      - "8081:8081"