version: '3.1'
services:
  postgres-server:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  validation-service-native:
    build:
      context: ./validation-service
      dockerfile: docker/native/Dockerfile
    ports:
      - "8082:8082"
  customer-service-native:
    build:
      context: ./customer-service
      dockerfile: docker/native/Dockerfile
    depends_on:
      - postgres-server
      - validation-service-native
    environment:
      - SPRING_PROFILES_ACTIVE=postgres,validation-native
    ports:
      - "8081:8081"
  neo4j-server:
    image: neo4j
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
  credit-check-service:
    build:
      context: ./credit-check-service
      dockerfile: src/main/docker/Dockerfile.native
    depends_on:
      - neo4j-server
    ports:
      - "8083:8083"
