version: '3.1'
services:
  postgres-server:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  customer-service-jvm:
    build:
      context: ./customer-service
      dockerfile: docker/jvm/Dockerfile
    depends_on:
      - postgres-server
    ports:
      - "8081:8081"