version: '3.1'
services:
  postgres-server:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  validation-service-jvm:
    build:
      context: ./validation-service
      dockerfile: docker/jvm/Dockerfile
    ports:
      - "8082:8082"
  customer-service-jvm:
    build:
      context: ./customer-service
      dockerfile: docker/jvm/Dockerfile
    depends_on:
      - postgres-server
      - validation-service-jvm
    environment:
      - SPRING_PROFILES_ACTIVE=postgres,validation-jvm
    ports:
      - "8081:8081"
  credit-details-service-jvm:
    build:
      context: ./credit-details-service
      dockerfile: docker/jvm/Dockerfile
    depends_on:
      - customer-service-jvm
    environment:
      - MICRONAUT_ENVIRONMENTS=dc-jvm
    ports:
      - "8080:8080"
  neo4j-server:
    image: neo4j
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
  credit-check-service-jvm:
    build:
      context: ./credit-check-service
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - neo4j-server
      - credit-details-service-jvm
    ports:
    - "8083:8083"
