server:
  port : 8082
spring:
  application:
    name: Validation-Service

logging:
  level:
    root: "INFO"

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
      show-components: always
