micronaut:
  application:
    name: credit-details-service
datasources:
  default:
    url: jdbc:h2:mem:default;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update

client:
  customer:
    url: http://localhost:8081
  interest-rate:
    url: https://esg8ls2e52.execute-api.eu-central-1.amazonaws.com/Prod
