@startuml
cloud {
[Frontend]
}
node "Customer service"{
[spring-app]
database "Postgres"
}

node "Validation Service" {
[kotlin-spring]
}

node "Credit Details Service" {
[micronaut-app]
database "H2"
}

node "Credit Check Service" {
[Quarkus-app]
database "Neo4j"

}

[Frontend] -down-> [spring-app]
[Frontend] -down-> [micronaut-app]
[Frontend] -down-> [Quarkus-app]

[spring-app] -left-> [kotlin-spring]
[spring-app] -down-> [Postgres]

[Quarkus-app] ->  [micronaut-app]
[Quarkus-app] ->  [spring-app]
[Quarkus-app] -down->  [Neo4j]

[micronaut-app] -down->  [H2]

@enduml