name: deploy-to-ebs

on:
  workflow_run:
    workflows: ["credit-check-service-pipeline"]
    branches: [develop]
    types: 
      - completed

env:
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Dockerrun.aws.json
        run: |
          cat Dockerrun.aws.json.template | AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} AWS_REGION=${{ env.AWS_DEFAULT_REGION }} envsubst > Dockerrun.aws.json
      - name: Upload output file
        uses: actions/upload-artifact@v1
        with:
          name: deploy-file
          path: Dockerrun.aws.json
      - name: Deploy to Elastic Beanstalk
        uses: hmanzur/actions-aws-eb@v1.0.0
        with:
          command: 'deploy InnolabGraalvm-env'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
