name: customer-service-pipeline
on:
  push:
    paths:
      - 'customer-service/**'
    branches: [ develop ]
  pull_request:
    paths:
      - 'customer-service/**'
    branches: [ develop ]
env:
  SERVICE_NAME: customer-service
  IMAGE_NAME: innolab-graalvm-customer-service
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  build-graalvm-ce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-jdk
      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The OpenJDK version to make available on the path
          java-package: 'jdk' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and test with Maven
        run: |
          cd ${{ env.SERVICE_NAME }}
          ./build.sh
      - name: Build image
        run: |
          cd ${{ env.SERVICE_NAME }}
          docker build -f docker/native/Dockerfile -t ${{ env.IMAGE_NAME }} .
      - name: Push to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_DEFAULT_REGION }}
          image: ${{ env.IMAGE_NAME }}