name: validation-service-pipeline
on:
  push:
    paths:
      - 'validation-service/**'
    branches: [ develop ]
  pull_request:
    paths:
      - 'validation-service/**'
    branches: [ develop ]
env:
  SERVICE_NAME: validation-service
  IMAGE_NAME: innolab-graalvm-validation-service
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  build-graalvm-ce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: "20.3.0"
          java-version: "java11"
          native-image: "true"
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and test with Maven
        run: |
          cd ${{ env.SERVICE_NAME }}
          ./build.sh
      - name: Build image
        run: |
          cd ${{ env.SERVICE_NAME }}
          docker build -f docker/native/Dockerfile -t ${{ env.IMAGE_NAME }} .
      - name: Push to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_DEFAULT_REGION }}
          image: ${{ env.IMAGE_NAME }}
